Move dcps base include up one level
LASAGNE-Open-Systems/LASAGNE-Core pull request #146
Opened 2018-09-19 04:53 UTC by james-ct

From feature(opendds) to odds_pusub.
When opendds feature is 0, the feautre(opendds) project is not loaded, therefore dcps_ts_flags key is not defined. ODDS project impls use this flag, and it causes an issue where MPC cannot find the flag, and it barfs, because requires are only processed after all keys are loaded.
This is the best way to fix it for all uses, I think.

2018-09-19 06:00 UTC, jwillemsen commented
Or use a dummy Custom as done in https://github.com/DOCGroup/ACE_TAO/pull/700

2018-09-19 11:19 UTC, james-ct commented
Thanks for the tip @jwillemsen that would also be a good fix. I'm happy to stick with the current one as the require removes the project once parsed anyway.

2020-05-29 23:08 UTC, ghost requested changes
DDSPubSub.mpc needs dcps

Something like:

`project(ODDS_PubSub) : opendds, dcps, DDSPubSub {`

2020-06-01 00:25 UTC, ghost approved these changes

2020-06-01 00:26 UTC, merged